import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'e2ee_test_bytes.dart';
import 'package:grid_pairing/grid_pairing.dart';

/// Numbers the phone half of the link must agree with, byte for byte.
///
/// Generated by `scripts/gen_e2ee_vectors.py` — a third implementation written
/// from the format description rather than transcribed from either side, so a
/// shared misreading of the spec shows up as a disagreement instead of being
/// blessed by both.
const _vectorsPath = 'test/vectors/e2ee_handshake.txt';

void main() {
  group('published vectors', () {
    final rows = _loadVectors();

    test('a handshake derives the transcript and keys the shared vector file '
        'names, so desktop and phone cannot drift apart silently', () {
      final handshakes = rows.where((row) => row.first == 'handshake');
      expect(handshakes, isNotEmpty, reason: 'vector file has no handshakes');
      for (final row in handshakes) {
        final name = row[1];
        final transport = E2eeTransport.fromWire(row[2])!;
        final relayHostId = row[3] == '-' ? null : row[3];
        final context = E2eeContext(
          protocol: E2eeSuite.grid.protocol,
          transport: transport,
          relayHostId: relayHostId,
        );
        final handshake = E2eeHandshake.validate(
          hello: E2eeHello(
            clientPublicKey: hexBytes(row[4]),
            clientNonce: hexBytes(row[5]),
            context: context,
          ),
          ready: E2eeReady(
            desktopPublicKey: hexBytes(row[6]),
            clientNonce: hexBytes(row[5]),
            desktopNonce: hexBytes(row[7]),
            context: context,
          ),
        );
        expect(handshake, isNotNull, reason: name);

        final transcript = encodeE2eeTranscript(handshake!);
        expect(transcript.length, int.parse(row[9]), reason: '$name length');

        final schedule = deriveE2eeKeySchedule(
          sharedSecret: hexBytes(row[8]),
          transcript: transcript,
          clientNonce: hexBytes(row[5]),
          desktopNonce: hexBytes(row[7]),
        );
        expect(hexOf(schedule.transcriptHash), row[10], reason: '$name sha');
        expect(hexOf(schedule.mobileToDesktopKey), row[11], reason: name);
        expect(hexOf(schedule.desktopToMobileKey), row[12], reason: name);
        expect(hexOf(schedule.sessionId), row[13], reason: '$name sid');
      }
    });

    test(
      'a frame header and nonce match the shared vector for every direction, '
      'payload kind and counter, including one past 32 bits',
      () {
        final frames = rows.where((row) => row.first == 'frame');
        expect(frames, isNotEmpty, reason: 'vector file has no frames');
        for (final row in frames) {
          final name = row[1];
          final sessionId = hexBytes(row[2]);
          final direction = E2eeDirection.values.firstWhere(
            (value) => value.wireByte == int.parse(row[3]),
          );
          final payloadKind = E2eePayloadKind.values.firstWhere(
            (value) => value.wireByte == int.parse(row[4]),
          );
          final counter = int.parse(row[5]);
          expect(
            hexOf(
              e2eeFrameHeader(
                sessionId: sessionId,
                direction: direction,
                payloadKind: payloadKind,
                counter: counter,
              ),
            ),
            row[6],
            reason: '$name header',
          );
          expect(
            hexOf(
              e2eeFrameNonce(
                sessionId: sessionId,
                direction: direction,
                payloadKind: payloadKind,
                counter: counter,
              ),
            ),
            row[7],
            reason: '$name nonce',
          );
        }
      },
    );
  });

  test(
    'the same encoder reproduces a foreign implementation published numbers '
    'under its labels, which is the evidence this port read the spec right',
    () {
      // Orca (stablyai/orca, src/shared/mobile-e2ee-v2-fixtures.ts) publishes
      // a known-answer vector for the design this channel was ported from.
      // Swapping in its four labels is the whole difference between the two
      // deployments, so reproducing its numbers proves the encoding — the
      // transcript layout and the key schedule — rather than proving that this
      // file agrees with itself.
      const orca = E2eeSuite(
        protocol: 'orca-mobile-e2ee',
        transcriptDomain: 'orca-mobile-e2ee/v2/transcript',
        saltLabel: 'orca-mobile-e2ee/v2/salt',
        sessionLabel: 'orca-mobile-e2ee/v2/session',
      );
      const context = E2eeContext(
        protocol: 'orca-mobile-e2ee',
        transport: E2eeTransport.relay,
        relayHostId: 'AbCdEf0123_-xyZ9',
      );
      final handshake = E2eeHandshake.validate(
        hello: E2eeHello(
          clientPublicKey: repeatedBytes(1),
          clientNonce: repeatedBytes(2),
          context: context,
        ),
        ready: E2eeReady(
          desktopPublicKey: repeatedBytes(3),
          clientNonce: repeatedBytes(2),
          desktopNonce: repeatedBytes(4),
          context: context,
        ),
      )!;

      final transcript = encodeE2eeTranscript(handshake, suite: orca);
      expect(transcript.length, 1347);

      final schedule = deriveE2eeKeySchedule(
        sharedSecret: repeatedBytes(5),
        transcript: transcript,
        clientNonce: repeatedBytes(2),
        desktopNonce: repeatedBytes(4),
        suite: orca,
      );
      expect(
        hexOf(schedule.transcriptHash),
        'ca6385f8bbf64a223fdd59587bfb67e2373891ce9e6d85ab41df8b7a20a168e3',
      );
      expect(
        hexOf(schedule.mobileToDesktopKey),
        'df17ff534df77fd3a30999f4e6200c8fcedefbb15d369301ca62c3cdfea9559a',
      );
      expect(
        hexOf(schedule.desktopToMobileKey),
        '71365fcf8212a6d63caf909ee28de3c8f689682ef298a374136055e0ab1cde4a',
      );
      expect(
        hexOf(schedule.sessionId),
        '339ae1f2bdff63481857d2813c2f19dd1f5aa4824705d5e5daeb25dae7b9196e',
      );
    },
  );
}

List<List<String>> _loadVectors() {
  final file = File(_vectorsPath);
  if (!file.existsSync()) {
    fail('vectors missing at $_vectorsPath — run scripts/gen_e2ee_vectors.py');
  }
  return [
    for (final line in file.readAsLinesSync())
      if (line.isNotEmpty && !line.startsWith('#')) line.split('\t'),
  ];
}
