// Framing for the USB link to grid-app — turns a byte stream into messages,
// and messages back into bytes.
//
// The mirror image of lib/infrastructure/panel/panel_frame.dart. Both halves
// are checked against ONE shared vector file
// (test/vectors/panel_frame.txt at the repo root, generated by
// scripts/gen_panel_vectors.py from the format description rather than from
// either implementation), so a shared misreading shows up as a disagreement
// instead of being blessed by both.
//
// Wire format, little-endian throughout:
//
//   A5 47 | ver:u8 | type:u8 | len:u16 | payload[len] | crc16:u16
//
// The magic is what the reader scans for after losing its place; the CRC is
// what separates a real frame from two bytes of noise that happened to look
// like the magic. That matters here more than on most links: the ROM and the
// second-stage bootloader print to this port before the app owns it, so the
// reader on the other end walks into the middle of a stream every boot.
//
// DELIBERATELY FREE OF ESP-IDF. This file compiles with a plain host compiler,
// which is how test/test_panel_frame.c runs the shared vectors on a laptop in
// milliseconds instead of on the device through a flash cycle.
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// PRODUCT-SCOPED, and that is the whole point of the second byte.
//
// This board is also the Harness dial: same Waveshare 466x466 round ESP32-S3, so the same USB identity
// (303a:1001, the SoC's own USB-Serial-JTAG, whose descriptor is in ROM). Harness's cable_frame.c was
// ported from this file, so until 2026-08-25 both products framed with A5 5A and greeted with the same
// three fields — nothing on the wire told them apart. Each side then decided "should I update this
// device?" from a VERSION NUMBER, which orders builds within one lineage and means nothing across two.
//
// What that did: grid-app saw a Harness dial, found its version "other than the bundled one", and
// flashed Grid firmware into it within seconds. Going the other way it is worse — once Harness's
// published version climbs past Grid's, each side reflashes what the other just wrote, ~3 MB and a
// reboot every 15 seconds, about 700 MB an hour into a flash rated in erase cycles.
//
// So the magic is the product. 0x47 is 'G'; Harness uses 0x48, 'H'. A decoder scanning for its own
// magic never matches the other's frames, so it never gets a `hello`, never learns a version, and
// never offers firmware — no cooperation from the other product required. A `product` field in the
// header would NOT do this: the other decoder still matches the magic, reads that byte as `ver`,
// derives a nonsense `len` and swallows a chunk of stream. Failing at byte one is a clean discard.
//
// 0xA5 stays the lead byte because it is outside ASCII, and that matters on this wire specifically:
// the ROM, the second-stage bootloader and the panic handler all write plain text to it, and a magic
// that can occur in that text resyncs the decoder onto garbage.
#define PANEL_MAGIC_0 0xA5
#define PANEL_MAGIC_1 0x47

// Bumped only when the ENVELOPE changes. The message vocabulary inside carries
// its own version in the `hello` handshake, so adding a message is not a
// framing change and must not bump this.
#define PANEL_FRAME_VERSION 1

#define PANEL_HEADER_BYTES 6   // magic(2) + ver(1) + type(1) + len(2)
#define PANEL_CRC_BYTES    2

// A bound on damage, not a capacity target: the largest thing this link really
// sends is a PCM chunk of about 1.3 KB. A corrupt length field can claim up to
// 65535 bytes, and with no ceiling the reader would sit waiting for a frame
// that is never coming while real frames pile up behind it — a hang, not a
// dropped message.
#define PANEL_MAX_PAYLOAD 8192

#define PANEL_MAX_FRAME \
    (PANEL_HEADER_BYTES + PANEL_MAX_PAYLOAD + PANEL_CRC_BYTES)

// Payload kinds. An unknown code is NOT rejected by this layer — it is handed
// up with its raw byte, so a newer grid-app talking to older firmware is a
// visible mismatch rather than a silently swallowed message.
#define PANEL_TYPE_JSON 0x01
#define PANEL_TYPE_PCM  0x02
// One slice of a firmware image, app → device only. Listed here with the other two rather than beside the
// code that consumes it: three payload kinds described in two files is how the third one gets forgotten.
#define PANEL_TYPE_FW   0x03

// CRC-16/CCITT-FALSE — poly 0x1021, init 0xFFFF, no reflection, no final xor.
//
// Named exactly because several 16-bit CRCs share the 0x1021 polynomial and
// differ only in init or reflection; the published check value for "123456789"
// is 0x29B1, which both test suites assert.
uint16_t panel_crc16(const uint8_t *data, size_t len);

// Write a frame carrying `payload` into `out`.
//
// Returns the frame length, or -1 when the payload is over PANEL_MAX_PAYLOAD
// or `out_cap` is too small. Failing here rather than truncating is deliberate:
// an oversized message is a bug on this side, and the far end could only ever
// report it as noise.
int panel_frame_encode(uint8_t type, const uint8_t *payload, size_t payload_len,
                       uint8_t *out, size_t out_cap);

// Called once per decoded frame. `payload` points into the decoder's own
// buffer and is only valid for the duration of the call — copy anything that
// must outlive it.
typedef void (*panel_frame_cb)(uint8_t version, uint8_t type,
                               const uint8_t *payload, size_t payload_len,
                               void *ctx);

// Reassembles frames from a byte stream that may start anywhere and contain
// anything.
//
// The buffer is a fixed array rather than a heap allocation: this runs on a
// device where a failed malloc mid-session is a worse outcome than a known
// 8 KB of BSS, and the ceiling is already fixed by PANEL_MAX_PAYLOAD.
typedef struct {
    uint8_t  buf[PANEL_MAX_FRAME];
    size_t   len;
    // The RATE is what matters: one bad frame at startup is the bootloader's
    // parting bytes and is expected, while a steady trickle during a session
    // means the two sides disagree about the format or the cable is bad. Those
    // are very different problems and look identical without a count.
    uint32_t corrupt_frames;
    uint32_t discarded_bytes;
} panel_decoder_t;

void panel_decoder_init(panel_decoder_t *d);

// Forget any partial frame. Call when the link is reopened: leftover bytes
// belong to a session that has ended, and carrying them across would put a
// stale half-frame in front of the next real one.
void panel_decoder_reset(panel_decoder_t *d);

// Feed `n` bytes and emit every frame they complete, in order.
//
// Never fails: everything arriving on this port is untrusted, and the only
// useful response to a byte that makes no sense is to step over it.
void panel_decoder_feed(panel_decoder_t *d, const uint8_t *data, size_t n,
                        panel_frame_cb cb, void *ctx);
