import 'package:xml/xml.dart';

/// One release, as the Sparkle appcast describes it.
///
/// The app reads this feed itself rather than letting Sparkle do it, because
/// Sparkle's own check can't run more often than hourly and goes silent in two
/// ways the app can't see — a version the user once told it to skip, and a check
/// that arrives while another update session is open. Reading a 700-byte XML and
/// comparing two integers has neither failure mode.
class AppcastRelease {
  const AppcastRelease({
    required this.shortVersion,
    required this.build,
    required this.downloadUrl,
  });

  /// Marketing version — `0.3.59`. What a person recognises, and the only part
  /// of this worth putting on screen.
  final String shortVersion;

  /// `CFBundleVersion` — `3059`. The number to **compare**: CI derives it as
  /// `major*1000000 + minor*1000 + patch` (`release.yml`, "Resolve version"), so
  /// it rises with every release, while [shortVersion] is only a label and
  /// sorts wrong the moment a number reaches double digits.
  final int build;

  /// Where the `.dmg` lives. Not used to install in this lane — Sparkle
  /// downloads it again through its own verified path — but carried so the
  /// banner can offer a manual download if that path ever fails.
  final String downloadUrl;
}

/// Namespace the `sparkle:` elements are declared in. Matched by namespace and
/// local name rather than by the literal prefix `sparkle:`, because a prefix is
/// a choice the feed's author makes and this one is generated by a shell script
/// that could reasonably rename it.
const String _sparkleNs = 'http://www.andymatuschak.org/xml-namespaces/sparkle';

/// The release in [feedXml] worth offering to a build at [installedBuild], or
/// null when there is nothing to offer.
///
/// Null covers every "don't nag" case at once: the feed is unreachable garbage,
/// it lists nothing, or its newest entry is not actually newer than what is
/// running. Erring towards null is deliberate — a missed notice is picked up by
/// Sparkle's own weekly check, while a wrong one puts a permanent banner in
/// front of someone who is already up to date.
AppcastRelease? updateFor(String feedXml, {required int installedBuild}) {
  final releases = _releases(feedXml);
  if (releases.isEmpty) return null;
  // Highest build wins rather than document order: an appcast may list several
  // releases, and Sparkle's own rule is "newest that applies", not "first".
  releases.sort((a, b) => b.build.compareTo(a.build));
  final newest = releases.first;
  return newest.build > installedBuild ? newest : null;
}

/// Every well-formed macOS entry in the feed. Entries missing a piece are
/// dropped rather than half-read: a release with no version can't be compared
/// and one with no enclosure can't be installed, so neither is worth offering.
List<AppcastRelease> _releases(String feedXml) {
  final XmlDocument document;
  try {
    document = XmlDocument.parse(feedXml);
  } on Object {
    return const [];
  }
  final out = <AppcastRelease>[];
  for (final item in document.findAllElements('item')) {
    final build = int.tryParse(_sparkleText(item, 'version') ?? '');
    final url = item
        .findElements('enclosure')
        .map((e) => e.getAttribute('url'))
        .whereType<String>()
        .firstOrNull;
    if (build == null || url == null || url.isEmpty) continue;
    out.add(
      AppcastRelease(
        // Falls back to the raw build number so the banner always has something
        // to name. A feed that omits the marketing string is malformed, not a
        // reason to withhold an update that is otherwise complete.
        shortVersion: _sparkleText(item, 'shortVersionString') ?? '$build',
        build: build,
        downloadUrl: url,
      ),
    );
  }
  return out;
}

/// The text of `<sparkle:[local]>` inside [item], or null when absent.
String? _sparkleText(XmlElement item, String local) {
  final element = item
      .findElements(local, namespaceUri: _sparkleNs)
      .firstOrNull;
  final text = element?.innerText.trim();
  return (text == null || text.isEmpty) ? null : text;
}
