import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:grid_app/infrastructure/panel/panel_frame.dart';

/// Frames the panel's C half must agree with, byte for byte.
///
/// Generated by `scripts/gen_panel_vectors.py` — a third
/// implementation written from the format description rather than transcribed
/// from either side, so a shared misreading of the spec shows up as a
/// disagreement instead of being blessed by both.
const _vectorsPath = 'test/vectors/panel_frame.txt';

typedef _Vector = ({
  String name,
  int typeCode,
  List<int> payload,
  List<int> frame,
});

List<_Vector> _loadVectors() {
  final file = File(_vectorsPath);
  if (!file.existsSync()) {
    fail('vectors missing at $_vectorsPath — run scripts/gen_panel_vectors.py');
  }
  final vectors = <_Vector>[];
  for (final line in file.readAsLinesSync()) {
    if (line.isEmpty || line.startsWith('#')) continue;
    final parts = line.split('\t');
    vectors.add((
      name: parts[0],
      typeCode: int.parse(parts[1]),
      payload: _hex(parts[2]),
      frame: _hex(parts[3]),
    ));
  }
  return vectors;
}

List<int> _hex(String hex) => [
  for (var i = 0; i < hex.length; i += 2)
    int.parse(hex.substring(i, i + 2), radix: 16),
];

void main() {
  final vectors = _loadVectors();

  test('the CRC is the published CCITT-FALSE variant, not a lookalike', () {
    // The one check value every CRC-16/CCITT-FALSE table agrees on. Several
    // 16-bit CRCs share the 0x1021 polynomial and differ only in init or
    // reflection, so naming the polynomial proves nothing — this does.
    expect(panelCrc16(utf8.encode('123456789')), 0x29B1);
  });

  test('vectors are actually loaded, so a silent empty run cannot pass', () {
    expect(vectors, isNotEmpty);
    expect(vectors.map((v) => v.name), contains('json_max_payload'));
  });

  group('encoding matches the shared vectors', () {
    for (final v in vectors) {
      test(v.name, () {
        final type = PanelFrameType.fromCode(v.typeCode)!;
        expect(encodePanelFrame(type, v.payload), v.frame);
      });
    }
  });

  group('decoding matches the shared vectors', () {
    for (final v in vectors) {
      test(v.name, () {
        final frames = PanelFrameDecoder().feed(v.frame);
        expect(frames, hasLength(1));
        expect(frames.single.typeCode, v.typeCode);
        expect(frames.single.payload, v.payload);
        expect(frames.single.version, kPanelFrameVersion);
      });
    }
  });

  test('a payload containing the magic bytes is not split at them', () {
    // The reader hunts for A5 5A, so a payload that contains that pair is the
    // case where a naive scanner cuts a frame in half and loses both.
    final payload = [0x01, ...kPanelMagic, ...kPanelMagic, 0x02];
    final frames = PanelFrameDecoder().feed(
      encodePanelFrame(PanelFrameType.pcm, payload),
    );
    expect(frames.single.payload, payload);
  });

  test('boot noise before the first frame is stepped over, not fatal', () {
    // What the ESP32 ROM and bootloader leave on the port before the firmware
    // owns it. The link has to start mid-stream every single time.
    final noise = utf8.encode('rst:0x1 boot: 0x8 SPIWP:0xee\r\n');
    final decoder = PanelFrameDecoder();
    final frames = decoder.feed([
      ...noise,
      ...encodePanelJson('{"t":"hello"}'),
    ]);
    expect(frames.single.text, '{"t":"hello"}');
    expect(decoder.discardedBytes, noise.length);
    expect(decoder.corruptFrames, 0);
  });

  test('a frame split across reads is assembled, one byte at a time', () {
    // A serial read returns whatever has arrived, so this is the normal case,
    // not an edge case: worst case is a frame arriving a byte per read.
    final frame = encodePanelJson('{"t":"split"}');
    final decoder = PanelFrameDecoder();
    final collected = <PanelFrame>[];
    for (final byte in frame) {
      collected.addAll(decoder.feed([byte]));
    }
    expect(collected.single.text, '{"t":"split"}');
  });

  test('two frames arriving in one read both come back, in order', () {
    final frames = PanelFrameDecoder().feed([
      ...encodePanelJson('{"n":1}'),
      ...encodePanelJson('{"n":2}'),
    ]);
    expect(frames.map((f) => f.text), ['{"n":1}', '{"n":2}']);
  });

  test('a corrupt frame is dropped and counted, and the next one survives', () {
    // The property that matters is recovery: one bad frame must cost one bad
    // frame, not the rest of the session.
    final bad = encodePanelJson('{"t":"bad"}').toList();
    bad[bad.length - 1] ^= 0xFF; // wreck the CRC
    final decoder = PanelFrameDecoder();
    final frames = decoder.feed([...bad, ...encodePanelJson('{"t":"good"}')]);
    expect(frames.single.text, '{"t":"good"}');
    expect(decoder.corruptFrames, greaterThanOrEqualTo(1));
  });

  test('a corrupt length does not stall the link waiting for bytes', () {
    // A wrecked length field can claim 64 KB. Without the ceiling the reader
    // would sit waiting for a frame that is never coming while real frames
    // queue up behind it — a hang, not a dropped message.
    final stalled = encodePanelJson('{"t":"x"}').toList();
    stalled[4] = 0xFF;
    stalled[5] = 0xFF;
    final decoder = PanelFrameDecoder();
    final frames = decoder.feed([
      ...stalled,
      ...encodePanelJson('{"t":"after"}'),
    ]);
    expect(frames.single.text, '{"t":"after"}');
  });

  test('a magic split across two reads still opens a frame', () {
    // The decoder keeps a trailing A5 rather than discarding it, because the
    // 5A may simply not have arrived yet.
    final frame = encodePanelJson('{"t":"edge"}');
    final decoder = PanelFrameDecoder();
    expect(decoder.feed(frame.sublist(0, 1)), isEmpty);
    expect(decoder.feed(frame.sublist(1)).single.text, '{"t":"edge"}');
  });

  test('an unknown type still decodes, so version skew is visible', () {
    // A newer firmware sending a type this build predates must arrive intact:
    // the layer above can then report a mismatch. Dropping it here would look
    // like a dead link instead.
    final frame = encodePanelFrame(PanelFrameType.pcm, [1, 2, 3]).toList();
    frame[3] = 0x7F; // a type no build defines
    final crc = panelCrc16(frame, start: 2, end: kPanelHeaderBytes + 3);
    frame[frame.length - 2] = crc & 0xFF;
    frame[frame.length - 1] = (crc >> 8) & 0xFF;

    final decoded = PanelFrameDecoder().feed(frame).single;
    expect(decoded.typeCode, 0x7F);
    expect(decoded.type, isNull);
    expect(decoded.payload, [1, 2, 3]);
  });

  test('encoding refuses an oversized payload where the bug is', () {
    expect(
      () => encodePanelFrame(
        PanelFrameType.pcm,
        List.filled(kPanelMaxPayload + 1, 0),
      ),
      throwsArgumentError,
    );
  });

  test('reset keeps the counters, because they are a trend not a tally', () {
    // A link that reconnects often is exactly the one worth measuring. Zeroing
    // on every reconnect would erase the history that tells "the bootloader
    // said hello again" from "these two disagree about the format".
    final decoder = PanelFrameDecoder()..feed(utf8.encode('rst:0x1 noise'));
    final discarded = decoder.discardedBytes;
    expect(discarded, greaterThan(0));

    decoder.reset();
    expect(decoder.discardedBytes, discarded);
  });

  test('reset drops a half-frame so a reopened port starts clean', () {
    // The bytes left over belong to a session that has ended; carrying them
    // across would put a stale half-frame in front of the new device's first.
    final frame = encodePanelJson('{"t":"partial"}');
    final decoder = PanelFrameDecoder()..feed(frame.sublist(0, 5));
    decoder.reset();
    expect(decoder.feed(frame.sublist(5)), isEmpty);
    expect(decoder.feed(frame).single.text, '{"t":"partial"}');
  });
}
