import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

import 'package:docx_creator/docx_creator.dart';
import 'package:file_selector/file_selector.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../infrastructure/logging/app_log.dart';
import '../../../shared/file_changes.dart';
import '../../../shared/folder_watch.dart';
import '../../files/logic/files_path.dart';
import 'docx_edit.dart';
import 'office_doc_chat.dart';
import 'office_doc_state.dart';

/// The file types Docs offers in its picker.
///
/// One entry, and the screen says so: `.docx` is the format this app can open
/// *and* write back without turning a document into plain text. Offering `.doc`
/// here would promise a conversion nothing in the app performs.
const _docsExtensions = ['docx'];

/// The document open in Docs, and the only way to open, edit, or save one.
///
/// Session state: closing the app closes the document. The file on disk is the
/// record — the app deliberately keeps no second copy of somebody's Word
/// document in `~/.grid`.
final officeDocProvider = NotifierProvider<OfficeDocController, OfficeDocState>(
  OfficeDocController.new,
);

class OfficeDocController extends Notifier<OfficeDocState> {
  /// The file exactly as it was opened — the baseline every save patches, so
  /// only the paragraphs the user changed are rewritten. Null when no document
  /// is open.
  DocxFile? _baseline;

  /// How many documents this session has opened — see [OfficeDocOpen.openId].
  int _opens = 0;

  /// Keeps a filesystem watcher alive on the open document's folder.
  ///
  /// Needed because the assistant's own announcements only cover what it does
  /// through its file *tools* (`agent_changes.dart` is fed by the agent adapters).
  /// Ask it to edit a `.docx` and it may well unpack, patch and repack the thing
  /// with a shell script instead — a write nothing in the app knows about. The
  /// filesystem does, and this is how Docs hears it.
  ///
  /// The folder rather than the file: a safe write is a temp file renamed over the
  /// original — which is what this app's own save does, and what Word does — and a
  /// watcher pinned to the old file misses that entirely.
  ProviderSubscription<void>? _folderWatch;

  @override
  OfficeDocState build() {
    // The assistant rewrites these files *while they are open* — that is what
    // Docs is for — and it announces every write on [fileChangesProvider]
    // (`agent_changes.dart`). Without listening, the screen goes on drawing the
    // version from before the edit, and a Save would then patch that stale
    // version and undo the assistant's work. See [_diskChanged].
    ref.listen(fileChangesProvider, (_, notice) {
      final open = state;
      if (open is! OfficeDocOpen) return;
      if (!notice.paths.contains(open.path)) return;
      unawaited(_diskChanged(open.path));
    });
    ref.onDispose(() => _folderWatch?.close());
    return const OfficeDocEmpty();
  }

  /// Watch the folder [path] lives in, and stop watching the last one.
  void _watchFolderOf(String path) {
    final folder = parentFolderOf(path);
    _folderWatch?.close();
    // Listened to rather than read: `folderWatchProvider` is autoDispose, so the
    // watcher lives exactly as long as this subscription — which is exactly as
    // long as the document is open.
    _folderWatch = folder == null
        ? null
        : ref.listen<void>(folderWatchProvider(folder), (_, _) {});
  }

  /// Ask for a document and open it. Does nothing when the user cancels.
  Future<void> pickAndOpen() async {
    final file = await openFile(
      acceptedTypeGroups: const [
        XTypeGroup(label: 'Word documents', extensions: _docsExtensions),
      ],
    );
    if (file == null) return;
    await open(file.path);
  }

  /// Make a new empty document, ask where it goes, and open it.
  ///
  /// Asks for the place *first*, before writing anything: a document has to live
  /// somewhere for Save to have a meaning, and an app that quietly parked new
  /// files in a folder of its own choosing would leave people hunting for their
  /// own work. Cancelling the picker creates nothing.
  ///
  /// The file itself is generated by `docx_creator` — the package already in the
  /// build for reading. Hand-writing the dozen XML parts a `.docx` needs is a
  /// second implementation of something a dependency does properly.
  Future<void> createBlank() async {
    final location = await getSaveLocation(
      suggestedName: 'Document.docx',
      acceptedTypeGroups: const [
        XTypeGroup(label: 'Word documents', extensions: _docsExtensions),
      ],
    );
    if (location == null) return;
    final path = location.path.toLowerCase().endsWith('.docx')
        ? location.path
        : '${location.path}.docx';
    state = OfficeDocOpening(path);
    try {
      // One empty paragraph, which is what Word's own blank document is: a body
      // with nothing in it has no paragraph to put the caret in.
      await DocxExporter().exportToFile(docx().p('').build(), path);
    } on Object catch (error, stack) {
      ref
          .read(appLogProvider)
          .failure(
            'office',
            'create blank failed: $path',
            error: error,
            stackTrace: stack,
          );
      state = OfficeDocFailed(
        "Grid couldn't create a document there. Pick another folder — one this "
        'computer lets apps write to.',
        path: path,
      );
      return;
    }
    await open(path);
  }

  /// Open the document at [path], replacing whatever is on screen.
  ///
  /// Unsaved edits in the current document are the caller's problem to ask about
  /// first — this controller does not second-guess a deliberate open.
  Future<void> open(String path) => _load(path, withChat: true);

  /// Read the open document off disk again, replacing what is on screen.
  ///
  /// Throws away unsaved edits, and says nothing about it: the only callers are
  /// the reload the screen offers *because* the file moved on, and the automatic
  /// one that runs when there is nothing to lose.
  Future<void> reloadFromDisk() async {
    final open = state;
    if (open is! OfficeDocOpen) return;
    // Not `withChat`: the conversation for this file is already the one on
    // screen, and asking for the file to be attached again would drop a second
    // copy of it onto the message being typed.
    await _load(open.path, withChat: false);
  }

  Future<void> _load(String path, {required bool withChat}) async {
    state = OfficeDocOpening(path);
    final read = await _readFile(path);
    switch (read) {
      case _ReadFailed(:final message, :final error):
        _baseline = null;
        ref
            .read(appLogProvider)
            .failure('office', 'open failed: $path', error: error);
        state = OfficeDocFailed(message, path: path);
      case _ReadOk(:final bytes):
        final docx = DocxFile.open(bytes);
        if (docx == null) {
          _baseline = null;
          ref
              .read(appLogProvider)
              .warn(
                'office',
                'not an editable .docx: $path (${bytes.length} bytes)',
              );
          state = OfficeDocFailed(
            'Documents saved as .docx open here. An older .doc has to be '
            'saved as .docx in Word first — and a file that arrived '
            'incomplete will not open either.',
            path: path,
          );
          return;
        }
        _baseline = docx;
        state = OfficeDocOpen(
          // Bumped on a reload too, and that is the point: the editor keys its
          // fields to this, so a document whose text came back different gets
          // fresh ones instead of showing the old words in them.
          openId: ++_opens,
          path: path,
          lines: List.unmodifiable(docx.lines),
          savedLines: List.unmodifiable(docx.lines),
          // Kept to tell a later change on disk from the app's own save.
          bytes: bytes,
          formats: docx.formats,
          pageWidthPx: docx.pageWidthPx,
        );
        _watchFolderOf(path);
        if (withChat) {
          // The document's own conversation comes with it — see
          // [officeDocChatProvider].
          ref.read(officeDocChatProvider.notifier).openFor(path);
        }
    }
  }

  /// The open document's file has just been written by somebody else.
  ///
  /// "Somebody else" is nearly always the assistant: it edits these files while
  /// they are open and announces every write on [fileChangesProvider]. What to do
  /// depends on whether there is anything here to lose — reload when there isn't,
  /// and say so when there is, rather than choosing for the user between their
  /// typing and the assistant's edit.
  Future<void> _diskChanged(String path) async {
    final read = await _readFile(path);
    if (read is! _ReadOk) return;
    final open = state;
    if (open is! OfficeDocOpen || open.path != path) return;
    // The app's own save lands here too when the folder happens to be watched,
    // and a reload for a file that hasn't actually changed would take the caret
    // with it. Comparing is cheaper than being clever about who wrote it.
    if (_sameBytes(read.bytes, open.bytes)) return;
    if (open.dirty) {
      state = open.copyWith(staleOnDisk: true);
      return;
    }
    await reloadFromDisk();
  }

  bool _sameBytes(Uint8List a, Uint8List? b) {
    if (b == null || a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }

  /// Replace one paragraph's text — what the Edit view calls on every keystroke.
  ///
  /// Paragraph [index] indexes the document's paragraphs, which is the same index
  /// `docx_edit.dart` patches by, so the thing under the caret and the thing
  /// written back are the same paragraph.
  void editLine(int index, String value) {
    final open = state;
    if (open is! OfficeDocOpen) return;
    if (index < 0 || index >= open.lines.length) return;
    if (open.lines[index] == value) return;
    final lines = [...open.lines]..[index] = value;
    // The save state clears with the edit: the message named a save of text that
    // is no longer what is here.
    _put(open, lines);
  }

  /// Break paragraph [index] in two at [at] — what Enter does.
  ///
  /// A real paragraph split, not a newline dropped into the text: a newline
  /// inside a paragraph is Word's *soft* break, which this editor keeps and
  /// writes back as one. Only this makes a new `<w:p>`.
  void splitLine(int index, int at) {
    final open = state;
    if (open is! OfficeDocOpen) return;
    if (index < 0 || index >= open.lines.length) return;
    final line = open.lines[index];
    final cut = at.clamp(0, line.length);
    final lines = [...open.lines]
      ..[index] = line.substring(0, cut)
      ..insert(index + 1, line.substring(cut));
    _put(open, lines);
  }

  void _put(OfficeDocOpen open, List<String> lines) => state = open.copyWith(
    lines: List.unmodifiable(lines),
    save: const OfficeSaveIdle(),
  );

  /// Write the edits back into the file they came from.
  Future<void> save() async {
    final open = state;
    final baseline = _baseline;
    if (open is! OfficeDocOpen || baseline == null) return;
    if (open.save is OfficeSaveRunning) return;

    final lines = open.lines;
    // The patch is built from the bytes this document was *opened* with, so
    // writing it over a file that has changed since would erase that change —
    // and the assistant changes these files while they are open. Checked here
    // rather than trusted to the notice on screen: the notice can be missed, and
    // what is at stake is somebody else's work.
    final onDisk = await _readFile(open.path);
    if (onDisk is _ReadOk && !_sameBytes(onDisk.bytes, open.bytes)) {
      state = open.copyWith(
        staleOnDisk: true,
        save: const OfficeSaveFailed(
          'This file changed on disk after you opened it — saving now would '
          'undo that change. Reload to take the new version; what you have '
          'typed here is replaced when you do.',
        ),
      );
      return;
    }
    state = open.copyWith(save: const OfficeSaveRunning());
    try {
      await _writeAtomically(open.path, baseline.save(lines));
    } on Object catch (error, stack) {
      ref
          .read(appLogProvider)
          .failure(
            'office',
            'save failed: ${open.path}',
            error: error,
            stackTrace: stack,
          );
      _fail(
        "Couldn't save to ${open.name}. Your edits are still here — check "
        'the file is not open in Word, then try again.',
      );
      return;
    }
    final latest = state;
    if (latest is! OfficeDocOpen || latest.path != open.path) return;
    // [savedLines] is what was written, not what the editor holds now: the user
    // may have typed on while the write ran, and those keystrokes are still
    // unsaved.
    state = latest.copyWith(savedLines: lines, save: const OfficeSaveIdle());
  }

  void _fail(String message) {
    final open = state;
    if (open is! OfficeDocOpen) return;
    state = open.copyWith(save: OfficeSaveFailed(message));
  }

  Future<_FileRead> _readFile(String path) async {
    try {
      return _ReadOk(await File(path).readAsBytes());
    } on FileSystemException catch (error) {
      return _ReadFailed(
        "The file isn't there any more, or this computer has no permission "
        'to read it.',
        error,
      );
    }
  }

  /// Writes [bytes] to [path] via a neighbouring temp file.
  ///
  /// The rename is what makes this safe: a crash or a full disk mid-write leaves
  /// the *original* document intact rather than half a zip, which for a Word
  /// file means the difference between "not saved" and "not openable". The temp
  /// file sits in the same folder on purpose — a rename is only atomic within
  /// one filesystem.
  Future<void> _writeAtomically(String path, List<int> bytes) async {
    final temp = File('$path.grid-save');
    await temp.writeAsBytes(bytes, flush: true);
    try {
      await temp.rename(path);
    } on FileSystemException {
      // Windows refuses a rename onto an existing file. Second-best there:
      // remove the original first, which is why the temp file is written and
      // flushed before anything touches it.
      await File(path).delete();
      await temp.rename(path);
    }
  }
}

/// The read either produced bytes or a sentence for the user — and the failure
/// carries the raw error too, because the log needs what the user must not read
/// (§6).
sealed class _FileRead {
  const _FileRead();
}

final class _ReadOk extends _FileRead {
  const _ReadOk(this.bytes);

  final Uint8List bytes;
}

final class _ReadFailed extends _FileRead {
  const _ReadFailed(this.message, this.error);

  final String message;
  final Object error;
}
