#!/usr/bin/env bash
# Rewrites pubspec.yaml's list of `assets/public_skill/**` directories.
#
# The catalog is one folder per publisher — `assets/public_skill/anthropic/…` —
# and that folder's name is the author shown on every card under it. Adding
# someone else's skills means a new folder beside it and a run of this script;
# no code changes.
#
# Flutter's asset directory entries are not recursive: `- assets/public_skill/`
# would ship the files sitting directly in it and none of the 200-odd folders
# underneath. So every directory that holds a file needs its own line, which is
# no kind of list to maintain by hand — after adding a skill, run this.
#
#   scripts/sync_public_skill_assets.sh
#
# Only the block between the two markers is touched; everything else in
# pubspec.yaml is left exactly as it was.
set -euo pipefail

cd "$(dirname "$0")/.."

ROOT="assets/public_skill"
PUBSPEC="pubspec.yaml"
BEGIN="  # >>> public_skill (generated by scripts/sync_public_skill_assets.sh)"
END="  # <<< public_skill"

if [ ! -d "$ROOT" ]; then
  echo "no $ROOT to sync" >&2
  exit 1
fi

# Every directory holding at least one file, deepest paths included, sorted so
# the diff is stable between runs on different machines.
entries=$(
  find "$ROOT" -type f ! -name '.DS_Store' \
    | sed 's|/[^/]*$||' \
    | LC_ALL=C sort -u \
    | sed 's|^|    - |; s|$|/|'
)

python3 - "$PUBSPEC" "$BEGIN" "$END" <<PY
import sys

path, begin, end = sys.argv[1], sys.argv[2], sys.argv[3]
entries = """$entries"""
text = open(path).read()
block = begin + "\n" + entries.rstrip("\n") + "\n" + end

if begin in text:
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    text = head + block + tail
else:
    text = text.rstrip("\n") + "\n" + block + "\n"

open(path, "w").write(text)
PY

echo "synced $(printf '%s\n' "$entries" | wc -l | tr -d ' ') directories into $PUBSPEC"
