#!/usr/bin/env bash
# Compile and run the framing codec's host test.
#
# The codec is deliberately free of ESP-IDF so this runs on a laptop in
# milliseconds instead of on the device through a flash cycle — which is the
# only reason it is practical to run it on every change.
#
# THE VECTOR FILE IS THE REPO'S, NOT THIS DIRECTORY'S. test/vectors/panel_frame.txt
# at the app root is generated by scripts/gen_panel_vectors.py — a THIRD
# implementation written from docs/panel-protocol.md rather than transcribed from
# either side — and the Dart half asserts against the same file. A copy under
# device/ would let this side drift and still pass, which is the one thing the
# shared file exists to prevent.
#
# The Dart half of the same link:
#   flutter test test/panel/          (from the repo root)
#
# Usage, from anywhere:
#   device/esp32-circle/scripts/test_frame.sh [path/to/panel_frame.txt]
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
OUT="${TMPDIR:-/tmp}/test_panel_frame"
VECTORS="${1:-$REPO/test/vectors/panel_frame.txt}"

cc -std=c99 -Wall -Wextra -Wpedantic -Werror -O1 \
    "$HERE/test/test_panel_frame.c" \
    "$HERE/main/panel_frame.c" \
    -o "$OUT"

"$OUT" "$VECTORS"
